#spring:
#  # 数据源
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  servlet:
#    multipart:
#          enabled: true
#          max-file-size: 50MB
#          max-request-size: 100MB
#server:
#  port: 7011
