#spring:
#  application:
#    name: redis-service
#
#  # 数据源
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#
#  #  Redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
##      password: 123456
#
#mybatis-plus:
#  configuration:
#    mapUnderscoreToCamelCase: true  # 自动将数据库下划线命名字段映射为实体类的驼峰命名属性。
#  mapper-locations: classpath*:mapper/**/*.xml # 指定 MyBatis 的 XML 映射文件位置，支持通配符匹配多路径下的 .xml 文件。
#
##端口
#server:
#  port: 7002
#
#
##日志级别
#logging:
#  level:
#    com.study.*: info
#
#
#
#
#
#
#
#
#
