#spring:
#
#  # 数据源
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#
##端口
#server:
#  port: 7000
#
##日志级别
#logging:
#  level:
#    com.study.example.*: info
#
